/**
 * Enhanced Clip Intelligence — Advanced clip analysis and scoring for smarter editing.
 * ════════════════════════════════════════════════════════════════════════════════════
 * Extends the basic motion-energy scoring in clipScoring.ts with:
 *   • Perceptual hash (pHash) for duplicate/similarity detection
 *   • Visual variety enforcement between adjacent clips
 *   • Color temperature classification (warm/cool/neutral)
 *   • Energy-level classification for narrative arc mapping
 *   • Composition heuristics (rule-of-thirds proximity)
 *
 * All algorithms are model-free (no ML dependencies). They parse FFmpeg metadata
 * outputs that are already generated by the main process's `scoreClip`,
 * `analyzeClipColor`, and `detectScenes` IPC handlers.
 */

// ─── Perceptual Hash (DCT-based pHash) ────────────────────────────────────────

/**
 * Computes a perceptual hash from a grid of luma values.
 * In practice, the main process extracts a small thumbnail via FFmpeg
 * (`-vf "scale=32:32,format=gray"`) and passes the pixel data here.
 * This function takes a 32×32 array of luma values (0-255) and returns
 * a 64-bit binary string hash using a simplified DCT approach.
 *
 * For integration with the FFmpeg pipeline, the main process should:
 *   ffmpeg -i input.mp4 -vf "thumbnail,scale=32:32,format=gray" -frames:v 1 -f rawvideo -
 * Then pass the 1024-byte buffer here.
 */
export function computePerceptualHash(lumaGrid: number[]): string {
    if (lumaGrid.length < 64) return '0'.repeat(64);

    // Downsample to 8×8 by averaging 4×4 blocks from 32×32
    const size = 8;
    const srcSize = Math.floor(Math.sqrt(lumaGrid.length));
    const blockSize = Math.max(1, Math.floor(srcSize / size));
    const reduced: number[] = [];

    for (let y = 0; y < size; y++) {
        for (let x = 0; x < size; x++) {
            let sum = 0;
            let count = 0;
            for (let dy = 0; dy < blockSize; dy++) {
                for (let dx = 0; dx < blockSize; dx++) {
                    const sy = y * blockSize + dy;
                    const sx = x * blockSize + dx;
                    const idx = sy * srcSize + sx;
                    if (idx < lumaGrid.length) {
                        sum += lumaGrid[idx];
                        count++;
                    }
                }
            }
            reduced.push(count > 0 ? sum / count : 0);
        }
    }

    // Simplified DCT: compare each value to the mean
    const mean = reduced.reduce((a, b) => a + b, 0) / reduced.length;
    return reduced.map(v => v > mean ? '1' : '0').join('');
}

/**
 * Computes Hamming distance between two perceptual hashes.
 * Returns 0 (identical) to 64 (completely different).
 */
export function hammingDistance(hash1: string, hash2: string): number {
    if (hash1.length !== hash2.length) return 64;
    let distance = 0;
    for (let i = 0; i < hash1.length; i++) {
        if (hash1[i] !== hash2[i]) distance++;
    }
    return distance;
}

/**
 * Returns a normalized similarity score (0-1) between two perceptual hashes.
 * 1.0 = identical, 0.0 = completely different.
 */
export function hashSimilarity(hash1: string, hash2: string): number {
    const maxBits = Math.max(hash1.length, hash2.length) || 64;
    return 1 - (hammingDistance(hash1, hash2) / maxBits);
}

/**
 * Threshold for considering two clips as "near-duplicates".
 * Similarity > 0.85 means the clips are visually very similar.
 */
export const DUPLICATE_THRESHOLD = 0.85;

/**
 * Threshold for "too similar to place adjacent" in a sequence.
 * Similarity > 0.70 means the clips should not be placed next to each other.
 */
export const ADJACENCY_SIMILARITY_THRESHOLD = 0.70;

// ─── Color Temperature Classification ────────────────────────────────────────

export type ColorTemperature = 'warm' | 'cool' | 'neutral';

/**
 * Classifies color temperature from FFmpeg signalstats metadata.
 * Uses the YAVG (luma average) and UAVG/VAVG (chroma averages) if available.
 * Falls back to a simplified luma-based classification.
 *
 * @param lumaAvg Average luma (0-255) from signalstats YAVG
 * @param satAvg  Average saturation (0-255) from signalstats SATAVG
 * @param hueDominant Dominant hue angle (0-360) if available from color histogram
 */
export function classifyColorTemperature(
    lumaAvg: number,
    satAvg: number,
    hueDominant?: number,
): ColorTemperature {
    // If we have hue information, use it for more accurate classification
    if (hueDominant !== undefined) {
        // Warm hues: 0-60° (reds, oranges, yellows) and 300-360° (magentas)
        if ((hueDominant >= 0 && hueDominant <= 60) || hueDominant >= 300) {
            return satAvg > 30 ? 'warm' : 'neutral';
        }
        // Cool hues: 180-270° (cyans, blues, purples)
        if (hueDominant >= 180 && hueDominant <= 270) {
            return satAvg > 30 ? 'cool' : 'neutral';
        }
    }

    // Fallback: warm clips tend to have higher luma + moderate saturation
    if (lumaAvg > 140 && satAvg > 40) return 'warm';
    if (lumaAvg < 100 && satAvg > 40) return 'cool';
    return 'neutral';
}

// ─── Energy Level Classification ──────────────────────────────────────────────

export type EnergyLevel = 'calm' | 'moderate' | 'high' | 'intense';

/**
 * Classifies a clip's energy level from motion score and scene change density.
 *
 * @param motionScore  0-100 from motionToScore()
 * @param sceneChanges Number of detected scene changes within the clip
 * @param clipDurationSec Clip duration in seconds
 */
export function classifyEnergy(
    motionScore: number,
    sceneChanges: number = 0,
    clipDurationSec: number = 5,
): EnergyLevel {
    // Scene change density (changes per second)
    const sceneChangeDensity = clipDurationSec > 0 ? sceneChanges / clipDurationSec : 0;

    // Composite energy = motion weight + scene change density bonus
    const compositeEnergy = motionScore + (sceneChangeDensity * 20);

    if (compositeEnergy > 80) return 'intense';
    if (compositeEnergy > 50) return 'high';
    if (compositeEnergy > 20) return 'moderate';
    return 'calm';
}

// ─── Narrative Arc Mapping ────────────────────────────────────────────────────

export type NarrativeBeat = 'establishing' | 'rising' | 'climax' | 'resolution';

/**
 * Maps energy levels to narrative beats for trailer construction.
 * The trailer follows a classic dramatic arc:
 *   establishing (calm/moderate) → rising (high) → climax (intense) → resolution (calm)
 */
export function mapToNarrativeBeat(
    energy: EnergyLevel,
    position: number, // 0-1 position in the sequence
): NarrativeBeat {
    // Early in the sequence: establishing shots
    if (position < 0.2) return 'establishing';

    // Late in the sequence: resolution
    if (position > 0.85) return 'resolution';

    // Map energy to the middle arc
    if (energy === 'intense') return 'climax';
    if (energy === 'high') return 'rising';
    if (energy === 'moderate') return position > 0.6 ? 'rising' : 'establishing';
    return 'establishing';
}

// ─── Clip Intelligence Metadata ───────────────────────────────────────────────

/**
 * Extended clip metadata computed by the intelligence pipeline.
 * This is stored alongside each clip and used by the generators
 * for smarter clip selection and placement.
 */
export interface ClipIntelligence {
    /** Perceptual hash for duplicate/similarity detection */
    pHash: string;
    /** Motion energy score (0-100) */
    motionScore: number;
    /** Color temperature classification */
    colorTemp: ColorTemperature;
    /** Energy level classification */
    energyLevel: EnergyLevel;
    /** Average luma (brightness) 0-255 */
    lumaAvg: number;
    /** Average saturation 0-255 */
    satAvg: number;
    /** Whether the clip contains detected silence */
    hasSilence: boolean;
    /** Number of scene changes detected within the clip */
    sceneChangeCount: number;
    /** When this intelligence data was generated */
    analyzedAt: number;
}

// ─── Context-Aware Transition Selection ───────────────────────────────────────

import type { TransitionType, TransitionStyle } from '../types';
import type { SegmentType } from './audioAnalysisCore';
import { SeededRandom } from './random';

/**
 * Context for making intelligent transition decisions.
 */
export interface TransitionContext {
    /** The current song segment (verse, chorus, drop, etc.) */
    segment: SegmentType;
    /** Energy level of the outgoing clip */
    outgoingEnergy: EnergyLevel;
    /** Energy level of the incoming clip */
    incomingEnergy: EnergyLevel;
    /** Whether this edit point falls on a detected beat */
    isOnBeat: boolean;
    /** Whether this edit point falls on a detected downbeat */
    isOnDownbeat: boolean;
    /** Whether this is a drop moment in the music */
    isDropMoment: boolean;
    /** Color temperature of outgoing clip */
    outgoingColorTemp: ColorTemperature;
    /** Color temperature of incoming clip */
    incomingColorTemp: ColorTemperature;
}

/**
 * Selects a transition based on content context, not just segment type.
 * This enhances the existing segment-based selection with clip-awareness.
 *
 * Rules:
 *  • Hard cuts for high-energy → high-energy (fast pace, no visual interruption)
 *  • Dissolves for calm → calm (emotional, smooth flow)
 *  • Impact transitions ONLY at drop moments / downbeats
 *  • Directional transitions for warm→cool color shifts (visual "travel")
 *  • Fade to black for energy drop (high → calm)
 */
export function selectContextAwareTransition(
    ctx: TransitionContext,
    allowedTransitions: TransitionType[] | undefined,
    style: TransitionStyle,
    rng: SeededRandom,
): TransitionType {
    if (style === 'cuts-only') return 'cut';

    // Build context-aware candidate list
    let candidates: TransitionType[] = [];

    if (ctx.isDropMoment || (ctx.isOnDownbeat && ctx.incomingEnergy === 'intense')) {
        // Drop moments: use impact transitions for maximum visual punch
        candidates = ['flash', 'glitch', 'rgb-split', 'zoom-through', 'cut'];
    } else if (ctx.outgoingEnergy === 'intense' && ctx.incomingEnergy === 'intense') {
        // High-to-high energy: fast cuts dominate
        candidates = ['cut', 'cut', 'cut', 'wipeleft', 'wiperight']; // weighted toward cuts
    } else if (ctx.outgoingEnergy === 'calm' && ctx.incomingEnergy === 'calm') {
        // Calm-to-calm: smooth, emotional transitions
        candidates = ['dissolve', 'fade', 'smoothleft', 'smoothright', 'hblur'];
    } else if (
        (ctx.outgoingEnergy === 'high' || ctx.outgoingEnergy === 'intense') &&
        (ctx.incomingEnergy === 'calm' || ctx.incomingEnergy === 'moderate')
    ) {
        // Energy drop: dramatic transition
        candidates = ['fadeblack', 'dissolve', 'fade'];
    } else if (
        (ctx.outgoingEnergy === 'calm' || ctx.outgoingEnergy === 'moderate') &&
        (ctx.incomingEnergy === 'high' || ctx.incomingEnergy === 'intense')
    ) {
        // Energy rise: building transitions
        candidates = ['wipeup', 'slideup', 'radial', 'circleopen'];
    } else if (ctx.outgoingColorTemp !== ctx.incomingColorTemp) {
        // Color temperature shift: directional transitions suggest "traveling"
        candidates = ['slideleft', 'slideright', 'wipeleft', 'wiperight', 'dissolve'];
    } else {
        // Default: segment-based selection (fall through to existing logic)
        candidates = ['cut', 'dissolve', 'fade', 'slideleft'];
    }

    // Beat-sync boost: on-beat transitions should be more decisive
    if (ctx.isOnBeat && !ctx.isDropMoment) {
        // Bias toward cuts on regular beats (keeping the rhythm tight)
        candidates = [...candidates, 'cut', 'cut'];
    }

    // Filter by allowed transitions (if user has restricted the set)
    if (allowedTransitions && allowedTransitions.length > 0) {
        const filtered = candidates.filter(t => allowedTransitions.includes(t));
        if (filtered.length > 0) candidates = filtered;
    }

    // Apply style constraint
    if (style === 'transitions-only') {
        candidates = candidates.filter(t => t !== 'cut');
        if (candidates.length === 0) candidates = ['dissolve'];
    }

    return rng.choice(candidates) as TransitionType || 'cut';
}

// ─── Visual Variety Enforcement ───────────────────────────────────────────────

/**
 * Reorders clips to maximize visual variety between adjacent positions.
 * Uses perceptual hash distance to ensure no two similar clips are adjacent.
 *
 * Algorithm: Greedy furthest-neighbor insertion.
 *   1. Start with the first clip.
 *   2. For each subsequent position, pick the clip from the remaining pool
 *      that is LEAST similar to the previously placed clip.
 *   3. If all remaining clips are above the similarity threshold, pick the
 *      one with the highest motion score (most "interesting").
 *
 * @param clips Array of clips with intelligence metadata
 * @param rng Seeded RNG for tie-breaking
 * @returns Reordered array of clip IDs
 */
export function enforceVisualVariety<T extends { id: string; intelligence?: ClipIntelligence }>(
    clips: T[],
    rng: SeededRandom,
): string[] {
    if (clips.length <= 1) return clips.map(c => c.id);

    const remaining = new Set(clips.map((_, i) => i));
    const result: number[] = [];

    // Start with a random clip
    const firstIdx = rng.randInt(0, clips.length);
    result.push(firstIdx);
    remaining.delete(firstIdx);

    while (remaining.size > 0) {
        const lastClip = clips[result[result.length - 1]];
        const lastHash = lastClip.intelligence?.pHash || '';

        let bestIdx = -1;
        let bestDistance = -1;

        for (const idx of remaining) {
            const candidateHash = clips[idx].intelligence?.pHash || '';
            if (!lastHash || !candidateHash) {
                // No hash data: use motion score as proxy for "difference"
                const motionDiff = Math.abs(
                    (clips[idx].intelligence?.motionScore || 50) -
                    (lastClip.intelligence?.motionScore || 50)
                );
                if (motionDiff > bestDistance) {
                    bestDistance = motionDiff;
                    bestIdx = idx;
                }
            } else {
                const dist = hammingDistance(lastHash, candidateHash);
                if (dist > bestDistance) {
                    bestDistance = dist;
                    bestIdx = idx;
                }
            }
        }

        if (bestIdx === -1) bestIdx = [...remaining][0]; // Shouldn't happen
        result.push(bestIdx);
        remaining.delete(bestIdx);
    }

    return result.map(i => clips[i].id);
}

/**
 * Checks if a proposed clip sequence has any adjacent pairs that are too similar.
 * Returns indices of problematic positions.
 */
export function findSimilarAdjacentPairs(
    hashes: string[],
    threshold: number = ADJACENCY_SIMILARITY_THRESHOLD,
): number[] {
    const problems: number[] = [];
    for (let i = 0; i < hashes.length - 1; i++) {
        if (hashes[i] && hashes[i + 1]) {
            const sim = hashSimilarity(hashes[i], hashes[i + 1]);
            if (sim > threshold) problems.push(i);
        }
    }
    return problems;
}
